version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    docker:
      - image: circleci/postgres:10-alpine
        environment: DB_HOST = ${DB_HOST}
          POSTGRES_DB=${DB_NAME}
          POSTGRES_USER=${DB_USER}
          POSTGRES_PASSWORD=${DB_PASS}
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./app/manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
